<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <RootNamespace>SDK.Comercial.Web</RootNamespace>
        <AssemblyName>SDK.Comercial.Web</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SDK.Comercial.Application\SDK.Comercial.Application.csproj" />
        <ProjectReference Include="..\SDK.Comercial.Domain\SDK.Comercial.Domain.csproj" />
        <ProjectReference Include="..\SDK.Comercial.Infrastructure\SDK.Comercial.Infrastructure.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    </ItemGroup>
    

</Project>
